version: "3"

services:
  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    container_name: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgweb:
    image: donnex/pgweb
    links:
      - postgres:postgres
    ports:
      - 8080:8080
    container_name: pgweb
    volumes:
      - pgweb-data:/opt/pgweb
    depends_on:
      - postgres

  web: &web_base
    build: .
    command: bin/rails server -b 0.0.0.0 -p 3000
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_HOST=minio
      - AWS_ENDPOINT=http://minio:9000
      - AWS_BUCKET_NAME=hr-note-qa-dev
      - BUNDLE_PATH=/usr/local/bundle
      - EDITOR=vim
      - RACK_ENV=development
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - WEBPACKER_DEV_SERVER_HOST=webpack
    ports:
      - 80:3000
    container_name: web
    volumes:
      - .:/docker-rails:cached
      - bundle:/usr/local/bundle:cached
      - dummy:/docker-rails/vendor
      - dummy:/docker-rails/log
      - dummy:/docker-rails/.git
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  webpack:
    <<: *web_base
    command: bin/webpack-dev-server
    ports:
      - 3035:3035
    container_name: webpack
    volumes:
      - .:/docker-rails:cached
      - bundle:/usr/local/bundle:cached
    depends_on:
      - web
    tty: false
    stdin_open: false

volumes:
  postgres-data:
    driver: local
  pgweb-data:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
  packs:
    driver: local
  dummy:
